#!/bin/bash

XPI=${1:-"site_block-0.1-fx.xpi"}

#Path to adb in ''
adb='adb'

# Replace this value to push to different release channels.
# Nightly = org.mozilla.fennec
# Aurora = org.mozilla.fennec_aurora
# Beta = org.mozilla.firefox_beta
# Release = org.mozilla.firefox
ANDROID_APP_ID=org.mozilla.firefox

# Push the add-on to your device to test
$adb push "$XPI" mnt/sdcard/"$XPI" #&& \

sed -e "s/NEW_BUILD/.\/$XPI/" install.html > /tmp/install.html
# Push an HTML page to link to add-on
$adb push /tmp/install.html mnt/sdcard/install.html #&& \

$adb shell am start -a android.intent.action.VIEW \
                   -c android.intent.category.DEFAULT \
                   -d file:///mnt/sdcard/install.html \
                   -n $ANDROID_APP_ID/.App && \
echo Pushed $XPI to $ANDROID_APP_ID
